### ISSUE TITLE
Making changes to blueprints causes script to want to update and revert my changes

### ISSUE THREAD

**Issue by uofirob** [Ornias1993/jailman#103]
I'm making changes to the blueprint script for Sonarr (for example) in order to add my custom locations for mount points (KidsTV) and to move the downloads directory to my /Downloads/Sonarr directory.  Whenever I change the install.sh to the way I like it, when I run install, it says my script is out of date and to run it again, during which it's nuked my changes. 

Is there any way to allow us to pass in the custom mountpoints to the config.yml so that if I want to customize that (it appears to be the only thing I'd want to change on Plex, Sonarr, Lidarr, Radarr) it doesn't get nuked?

**Comment by Ornias1993** [comment]
You can point the update script to your own repo, that should prevent it from getting nuked.

You might also be able to add blueprints without issues (I dont think the got updater destroys new files).

However: the difference between blueprints and jails: blueprints are not supposed to be changed by the end-user.

Hence i’ll close this

**Comment by colemamd** [comment]
Commenting despite already closed, another option is to find the gitupdate command in jailman.sh and comment it out.

**Comment by Ornias1993** [comment]
note: v1.3 auto updater will update the remote/branch the repo is set to, not our global config.
Just pushed those changes to a PR yesterday :)

**Comment by Ornias1993** [comment]
@uofirob On community request I reprioritised the auto-update fix.
It should now be included in 1.2.3 and can already be reviewed. See: #133
