### ISSUE TITLE
Add Unifi and UnifiPoller

### ISSUE THREAD

**Issue by Ornias1993** [Ornias1993/jailman#11]
Adding Unifi wouldn't be that much of an improvement over the FreeNAS plugin at first sight.

However, doing it "our way" we would be able to also include the Unifi Poller to connect it with InfluxDB. This is possible because Unifi Poller has just also released it's FreeBSD version, after testing by yours truely and others.

**Comment by Ornias1993** [comment]
PR's to include this can now be PR'ed agaist the jails/unifi branch.

**Comment by Ornias1993** [comment]
I'm going to consider this blocked till InfluxDB is in, better include UnifiPoller right at the same time as we create the initial Unifi Jail

**Comment by colemamd** [comment]
Is it your intention to have two separate jails for Unifi & UnifiPoller?

**Comment by Ornias1993** [comment]
No. They are planned as one and the same.
I see no reason to seperate the to and it would make things needless complicated.

**Comment by Ornias1993** [comment]
Unblocked due to inclusion of InfluxDB jail into the dev branch

**Comment by colemamd** [comment]
#75
