### ISSUE TITLE
Add basic Quicksync support to Plex

### ISSUE THREAD

**Issue by Ornias1993** [Ornias1993/jailman#20]
Because we are not limited by the FreeNAS plugin system, it's very well possible to introduce quicksync hardware encoding for Intel gen4-7 CPU's.

This is a rough explaination/tutorial how to do it:
https://github.com/kern2011/Freenas-Quicksync

This is just the jail side of things, it will just enable the jail to support hardware encoding. it WILL NOT include host fixes and thus WILL NOT enable quicksync.

**Comment by Ornias1993** [comment]
It isn't that hard actually, just put this into the script and test it:
https://github.com/kern2011/Freenas-Quicksync

**Comment by thorsteneb** [comment]
This could be fun. There are some caveats.

- Need to somehow detect that an Intel iGPU is present (lspci and grep?), do a quick kldload and verify that /dev/dri comes in
- Need to identify generation and install the right Intel drivers. Exhaustive list could get hard to maintain
- This breaks IPMI, and there is NO way around that. At the very least there needs to be a prominent warning in docs about that, and during install

**Comment by Ornias1993** [comment]
No. thats not how far I was planning to go with this.
It will not detect intel cpu's. It will just inplement a few of the tweaks, not full quicksync support.

So no, it will not do any of the things you list. So please let me worry about this one ;)

**Comment by Ornias1993** [comment]
I called it "basic support" for a reason.
It would include some basic hooks for users to enable support. Not full blown support.

**Comment by Ornias1993** [comment]
With more detail:
This will just be the Jail portion to prepare for quicksync support on the jail side.
Just things like the driver pkg's etc.

Mostly just the things under: "From the Plex jail console:" in the refered guide.
It's not supposed to be fully documented nor supported yet.

**Comment by Ornias1993** [comment]
As it's mostly a personal note for one of my personal pet projects, i'm going to lock this to prevent endless discussions due to me not fully documenting this brainfart.

**Comment by Ornias1993** [comment]
@thorsteneb I just read your changes... It means I only need to add the video-group command on the jail side. Pushing changes now.

Thanks for your work on upstream!
