### ISSUE TITLE
Run Multiple Installs of Software

### ISSUE THREAD

**Issue by mikestecker** [Ornias1993/jailman#26]
It would be great if we could install multiple copies of the same software. For example: Radarr. Reason being is that this is the recommended way (from what I understand) to separate 4K downloads from HD is to run a standard install of Radarr for your normal downloads, and a separate install of Radarr to handle 4K downloads.

**Comment by Ornias1993** [comment]
This sounds doable...
Requires a few steps:

- Seperate the different kinds of names: 
'jail_name' (name of config entry and final jail name) 
and 
'blueprint_name' (name of the blueprint in the jails folder, which could be renamed blueprints)

- Turn all references of jailname into variables to blueprint_name and jail_name respectively.

In terms of priority I think it would be nice to combine this with #3 and #25 which are both planned after I get some more jails in (so slightly low in priority, but not to be forgoten) :)

**Comment by Ornias1993** [comment]
I might be able to combine this into v1.2.0 if I can combine it with #43 in such a way that it doesn't break current config files.

If it does brake current config, it will be delayed till v2.0
