### ISSUE TITLE
Add CrashPlan

### ISSUE THREAD

**Issue by mikestecker** [Ornias1993/jailman#30]
I know this ask might be a long shot but it would be great to get the [CrashPlan Small Business client for Linux](https://support.code42.com/Administrator/Small_Business/Get_started_with_CrashPlan_for_Small_Business/CrashPlan_for_Small_Business_requirements) installed as that is my cloud backup solution.

**Comment by Ornias1993** [comment]
As far as I can find, Crashplan on FreeBSD is kinda "meh" when it comes to stability and I don't have a way (nor the time) to test it. Be aware this only does jails, not VM's and VM's are not going to be included.

Someone else is free to submit it though :)

**Comment by Ornias1993** [comment]
@mikestecker Does crashplan SMB require a paid subscription or not?
If it does, I think i'm gonna VETO this one and add the requirement that jails can't require a paid subscription 
(Requiring a paid subscription makes it harder to find people to maintain a jail, which hurts the general stability goal of this project)

**Comment by mikestecker** [comment]
> @mikestecker Does crashplan SMB require a paid subscription or not?
> If it does, I think i'm gonna VETO this one and add the requirement that jails can't require a paid subscription
> (Requiring a paid subscription makes it harder to find people to maintain a jail, which hurts the general stability goal of this project)

Yes, it is a subscription unfortunately. But only $5/mo subscription per server. It's the cheapest unlimited cloud backup I can find. I currently use [this docker](https://github.com/jlesage/docker-crashplan-pro) on my other server that I am migrated off to move to FreeNAS.

**Comment by Ornias1993** [comment]
In that case I'm going to Veto it (at least for the time being...)...
Not saying it would never happen, but not anytime soon....
