### ISSUE TITLE
Base Jails

### ISSUE THREAD

**Issue by thorsteneb** [Ornias1993/jailman#52]
I notice you don't default to base jails, and don't have an option to choose base jails.

I think base jails are the most likely choice for long-running jails. It also allows upgrading all jails to a new iocage release in one go, when upgrading FreeNAS to a new major version.

Your take on base jails as the default, or as a configurable option?

Edit: As per https://www.ixsystems.com/community/threads/iocage-jail-type-base-jail-vs-clone-which-to-choose.82639/ , clone jails are best suited to "nuke and rebuild" on upgrade, and base jails are better suited for jails that survive across FreeNAS releases.

**Comment by Ornias1993** [comment]
Considering this solution is primarily designed to make us able to actually "nuke and rebuild" with a single command, I think clone fits this project quite nicely ;)

**Comment by thorsteneb** [comment]
Would you accept a PR that makes basejail an option?

**Comment by Ornias1993** [comment]
> Would you accept a PR that makes basejail an option?

An option? No I think that increases the error and bug vector in a degree I can't accept into the project... Not without testing CI and such.

But, i've read into it... and I think going base jails as default (and only option) might be prefered. Using base jails would create a more stable/default environment and would infact streamline the update process very much.

While I don't like the extra space requirements and such, Security, updateability and more "standardised" environments might be more important.

I think thats also why IXsystems uses basejails for plugins I guess...

Anyhow, I you want to PR a move to basejails I'm all for it :)

**Comment by thorsteneb** [comment]
I am glad you say that. Particularly since your project doesn't currently move jail data outside the jail as a matter of course (Plex metadata as an example), "blow away and redo" isn't great - and the space savings are gone once you upgrade a clone jail.

Plus, as you say, so much easier to upgrade all jail releases in one go, rather than needing to do that jail by jail.

**Comment by Ornias1993** [comment]
"I am glad you say that. Particularly since your project doesn't currently move jail data outside the jail as a matter of course (Plex metadata as an example"

Thats not true, I'm actually quite vocal about not having data inside the jail. The fact i'm not done with plex is just one slight oversight. I'm simply not done with plex completely yet (as shown by the open issues about it)

**Comment by thorsteneb** [comment]
Successful in most things, with one exception. This may be fairly easy to resolve.

```
root@freenas[~/jailman]# ./jailman.sh -i jacket radarr sonarr lidarr transmission tautulli organizr kms nextcloud mariadb bitwarden
...
Successfully added mount to radarr's fstab
ln: /usr/bin/mono: Read-only file system
Command: ln -s /usr/local/bin/mono /usr/bin/mono failed!
```

In radarr install.sh:
```
iocage exec radarr ln -s /usr/local/bin/mono /usr/bin/mono
```

Whytho?

I am hoping that ln is not required to actually run radarr. I'd be a little shocked if it was.

Same story for the other jails using mono.

**Comment by thorsteneb** [comment]
I have a notion to improve the update and upgrade functionality with basejails in mind. Will need careful testing, putting a note here to remember this later.

Proposed functionality.

Single-jail -u or -g -- no changes
Multi-jail -u -or -g -- run iocage update/upgrade on all clone jails, run it on the first basejail of the list, but not on subsequent ones; do run the jail's own script on each, of course.
To be discussed: jail restart strictly necessary on update? For most jails, restarting the service (handled by the jails own script) is sufficient, and faster.

**Comment by Ornias1993** [comment]
I suggest moving this to a seperate issue ;)
But yes, that is a good option and I don't see any problems with it.

Restarts aren't strictly required, no... But it isn't much of a burden to do so and prevents/uncovers unforseen issues. I always restart my jails after an update, just to be sure and would suggest anyone to do so.
