### ISSUE TITLE
Rename plexpass to beta and document it

### ISSUE THREAD

**Issue by Ornias1993** [Ornias1993/jailman#54]
Rename plexpass to beta and Add documentation in the readme that clarifies it is beta code and not required to use Plexpass features. Maybe also add a comment to the example config.

**Comment by thorsteneb** [comment]
Might even consider renaming the variable in the example config from "plexpass" to "beta" to make this behavior abundantly clear

**Comment by Ornias1993** [comment]
uhmm... I personally prefer to stay close as possible to other implementations.

**Comment by thorsteneb** [comment]
I prefer to confuse users as little as possible, and boy does the "plexpass" naming confuse users.

See FreeNAS 11.3 - in the plugin list, they are now calling the plexmedia-plexpass option the "beta" option, for that is what it is.

There used to be a separate package with PlexPass features, hence the naming. That was merged into the base stable package a while ago, and now all that plexmedia-plexpass does is give users beta code. I think people should make that decision very clearly, and not think for a second that they need that code to use PlexPass features.

**Comment by Ornias1993** [comment]
> See FreeNAS 11.3 - in the plugin list, they are now calling the plexmedia-plexpass option the "beta" option, for that is what it is.

If they changed that for the plugin (wasn't the case last time I checked), we should too.
