### ISSUE TITLE
Additional documentation on permissions etc required (folder not wirtable)

### ISSUE THREAD

**Issue by coconutoil** [Ornias1993/jailman#65]
Hi,

All my media is set to **/mnt/store/movies** as **media:media** including the movies directory itself, and yet after installing radarr via the script, and trying a bulk import I get 
**"Folder is not writable by user radarr"** in the radar GUI when choosing **/mnt/movies** as import directory.
I ran into this problem too when trying other scripts which is why I came to this project, hoping it would take care of all this.
Maybe it should be documented what the fundamental requirements on the datasets are?
I'm kind of lost and would love some realtime chat advice. Could we create a Telegram channel or something for this project?

**Comment by Ornias1993** [comment]
I'm not done with setting up the permissions for the media servers yet myself.
You also seem to have custom mountpoints...

It seems fair to first set the permissions ourselves, before we go support custom setups ;)

It seems I have forgoten to create an issue about it though (although it's mentioned in #63 )
Here you go: #66

**Comment by Ornias1993** [comment]
(Closing this till at least there are permissions to document)
