### ISSUE TITLE
Document assumed directory layout for included installers

### ISSUE THREAD

**Issue by coconutoil** [Ornias1993/jailman#68]
I think we need to document and stardardise the general media store layout, like
`/mnt/tank1/media/etc`
as the Radarr script will automatically mount the subdirectory "movies":
`createmount radarr ${global_dataset_media}/movies /mnt/movies `

For example my shows are stored in 
`"${global_dataset_media}/tv_shows" `
but the Sonarr script mounts 
`"${global_dataset_media}/shows"`,
so at this stage I think having the basic assumed layout handy in the config script or somewhere would be beneficial so beforehand we can either edit (in config.yml) or restructure our data accordingly. I think long-term this will be essential.

As a side note (me, on autopilot) renamed my config.yml.sample to config.**yaml** and spent an hour trying to troublehsoot why nothing was installing or working when it should be! (with my dyslexia!).. Damn old ruby days ;)

**Comment by Ornias1993** [comment]
> I think we need to document and stardardise the general media store layout

The general media layout is standardised. It's the same in every jail.

> For example my shows are stored in
> "${global_dataset_media}/tv_shows"
> but the Sonarr script mounts
> "${global_dataset_media}/shows",

Yes, this is expected and the layout should infact be documented. Thanks for reporting!

> so at this stage I think having the basic assumed layout handy in the config script

I'm hesitant to bloat the config file any more than it already is. It would be preferable to have it as KISS as possible, to not overload new users with (customisation related) info.

We have a wiki for it, so i'll put in a change for 1.2 to add the layout to the wiki.
