### ISSUE TITLE
Add "ALL" shortcut to install all jails

### ISSUE THREAD

**Issue by Ornias1993** [Ornias1993/jailman#7]
A "ALL" shortcut to install all jails in the config.yml file, would be amazing and speed up deployment bigtime.
This basically need a script to generate a list of distinct jailnames from all the 'jaillname_*' variables. Afther which it's enough to just push those into the already present (re)install, update and destroy loops.

**Comment by thorsteneb** [comment]
Outlook to the future, if you do implement this, consider warning users that it's meant as a dev testing tool only.

I can see a future where jailman knows how to install alternatives.
- Emby, or Plex. People probably won't run both.
- nginx, or traefic. Again, people probably won't run both.

Other apps that exist in different flavors, for people to pick between.

**Comment by Ornias1993** [comment]
Hmm... interesting point...
I never realised we might implement alternatives... How stupid of me!

I that case I think I might even opt not to include a "ALL" shortcut.
Just for dev it's not worth adding the code for people that are very well capable of copy-pasta :P

Certainly because I don't want any prompts in the future at all. It's meant for hands-off installation... prompts with alternatives needlessly complicates things. So I'm actually opting to drop this completely.
