### ISSUE TITLE
Enhancement: Creation of portsnap directed by jails/JAILNAME/config.yml

### ISSUE THREAD

**Issue by thorsteneb** [Ornias1993/jailman#89]
Currently, portsnap is created and mounted into a jail by default, whether it is useful there or not.

I suggest to instead, introduce a parameter that can be specified globally (default) and overridden on a per-jail basis, via config.yml, on whether to install portsnap at all.

Likely also useful: A parameter to determine which ports to install, if portsnap is being brought in.

This might all already be in flight and I am just catching an in-between half-finished build.

**Comment by Ornias1993** [comment]
> Currently, portsnap is created and mounted into a jail by default, whether it is useful there or not.

Portsnap is created and mounted to every jail indeed.
Portsnap is shared between all jails, so it doesn't install it multiple times.

> I suggest to instead, introduce a parameter that can be specified globally (default) and overridden on a per-jail basis, via config.yml, on whether to install portsnap at all.

We are moving away from jails to blueprints (terminology maters, see the current PR). I could make this a per-blueprint setting, it was forced during jail install to move it away from the install.sh file and make sure it isn't user-changable. With the new blueprints system this can be changed.

> A parameter to determine which ports to install, if portsnap is being brought in.

It's a shared repository ONLY, it doesn't install anything. Installing from ports is somethings that is already done in a per-jail basis.

**Comment by Ornias1993** [comment]
Blueprint PR, now also makes port fetch a per-blueprint setting.
But it still links the global ports dataset to all jails.

I think that would solve your issues when merged.
